FROM golang:1.19
# FROM golang:1.19.1-alpine3.15
RUN apt update
WORKDIR /go/src

# COPY . .

# RUN go get "github.com/gin-gonic/gin"
# RUN go get "github.com/go-sql-driver/mysql"

CMD ["go", "run", "main.go"]
