version: '3.8'

volumes:
  imtask_volume:
    name: imtask_mysql_vol

services:
  go:
    container_name: go-container
    build:
      context: ./golang
      dockerfile: Dockerfile
    # env_file:
    #   - './golang/.env'
    environment:
      - DRIVER
      - DB_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - 8080:8080
      - 8081:8081
    tty: true
    volumes:
      - type: bind
        source: ./golang/src
        target: /go/src
    depends_on:
      - db-dev
    # networks:
    #   - golang_network

  db-dev:
    container_name: mysql-container
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    tty: true
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      # data perpetualation
      # Docker volume
      - type: volume
        source: imtask_volume
        target: /var/lib/mysql
      - type: bind
      # initialize mysql in a container
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
